[build-system]
requires = ["rust", "cmake", "setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rholearn"
version = "0.0.0"
description = "Metatensor-torch framework for learning electronic densities decomposed on a basis"
authors = [{name = "Joseph W. Abbott", email = "joseph.william.abbott@gmail.com"}]
dependencies = [
    "ase",
    "ipython",
    "jupyter",
    "jupyterlab",
    "numpy",
    "pandas",
    "pytest",
    "py3dmol",
    "sympy",
    "wheel",

    # Dependencies from the COSMO (+ friends) stack
    "chemfiles",
    "chemiscope",
    "metatensor[torch]",
    "rascaline-torch @ git+https://github.com/luthaf/rascaline@0311925f9aba803a0744a48d448567a9b65316e1#subdirectory=python/rascaline-torch",
    "vesin",
    "wigners",

    # Extra dependencies
    "cube_toolz @ git+https://github.com/funkymunkycool/Cube-Toolz",
]

[tool.setuptools]
packages = [
    "rholearn",
    "rholearn.aims_interface",
    "rholearn.settings",
    "rholearn.utils",
]
