# Cross-validation splits (number of frames)
N_TRAIN: 16
N_VAL: 8
N_TEST: 8

# Other user settings here:
# ...

DESCRIPTOR_HYPERS:
  descriptor_type: rho2
  spherical_expansion_hypers:
    cutoff:
      radius: 3.0
      smoothing:
        type: ShiftedCosine
        width: 0.1
    density:
      type: Gaussian
      width: 0.2
    basis:
      type: TensorProduct
      max_angular: 4
      radial:
        type: Gto
        max_radial: 7

# For training the model
TRAIN:
  batch_size: 2
  n_epochs: 501  # number of total epochs to run. End in a 1, i.e. 1001.
  restart_epoch: null  # epoch of last saved checkpoint, or None for no restart
  val_interval: 50  # validate every x intervals
  log_interval: 50  # epoch interval at which to log metrics
  checkpoint_interval: 100  # save model and optimizer state every x intervals

# For model evaluation
EVAL:
  subset_size: 5  # only perform model evaluation on 5 structures
