name: rho
dependencies:
  - python=3.11
  - pip
  - rust
  - cmake
  - pip:
    - ase
    - chemfiles
    - chemiscope
    - ipython
    - jupyter
    - jupyterlab
    - numpy
    - pandas
    - pytest
    - py3dmol
    - sympy
    - vesin
    - wigners
    - wheel