# Define a seed. This is used to shuffle frame indices for cross-validation splits and
# initialize model parameters
SEED: 42

# Rascaline SphericalExpansion hyperparameters
SPHERICAL_EXPANSION_HYPERS:
  cutoff: 3.0  # Angstrom
  max_radial: 8  # Exclusive
  max_angular: 5  # Inclusive
  atomic_gaussian_width: 0.3
  radial_basis:
    Gto: {}
  cutoff_function:
    ShiftedCosine:
      width: 0.1
  center_atom_weight: 1.0
  radial_scaling:
    Willatt2018:
      exponent: 7
      rate: 1
      scale: 2.0

HIDDEN_LAYER_WIDTHS: null  # null for linear model

PREDICTED_DOS:
  min_energy: -10.0  # eV
  max_energy: 10.0  # eV
  interval: 0.05  # eV
  sigma: 0.3  # eV
  reference: Fermi # or Hartree

DOS_SPLINES:
  min_energy: -10.0 # eV
  max_energy: 13.0 # eV 
  interval: 0.05 # eV

# For training the model
TRAIN:
  device: cpu
  dtype: float64  # important for model accuracy
  batch_size: 1
  val_batch_size: 1 # Use the highest number that can fit in the memory
  n_epochs: 500
  restart_epoch: null  # epoch of last saved checkpoint, or None for no restart
  val_interval: 1  # validate every x intervals
  log_interval: 100  # epoch interval at which to log metrics
  checkpoint_interval: 100  # save model and optimizer state every x intervals

# Args for Adam optimizer
OPTIMIZER_ARGS:
  lr: 0.001

# For ReduceLRonPlateau
SCHEDULER_ARGS:
  gamma: 0.1
  patience: 200
  threshold: 0.00001
  min_lr : 0.00001
