# Define a seed. This is used to shuffle frame indices for cross-validation splits and
# initialize model parameters
SEED: 42

# featomic SphericalExpansion hyperparameters
SPHERICAL_EXPANSION_HYPERS:
  cutoff:
    radius: 3.0
    smoothing:
      type: ShiftedCosine
      width: 0.1
  density:
    type: Gaussian
    width: 0.3
    scaling:
      type: Willatt2018
      exponent: 7
      rate: 1
      scale: 2.0
  basis:
    type: TensorProduct
    max_angular: 5
    radial:
      type: Gto
      max_radial: 7

# NN architecture
HIDDEN_LAYER_WIDTHS: null  # null for linear model

# Learn an adaptive energy reference
USE_ADAPTIVE_REFERENCE: false

# DOS parameters
TARGET_DOS:
  adaptive_reference: true  # whether or not to use an adaptive (learnable) energy reference
  max_energy_buffer: 10  # predict DOS grid 10 eV less than max spline energy
  standardize: false

# For training the model
TRAIN:
  device: cpu
  dtype: float64  # important for model accuracy
  batch_size: 1
  val_batch_size: null  # use the highest number that can fit in the memory
  n_epochs: 500
  restart_epoch: null  # epoch of last saved checkpoint, or None for no restart
  val_interval: 1  # validate every x intervals
  log_interval: 100  # epoch interval at which to log metrics
  checkpoint_interval: 100  # save model and optimizer state every x intervals

# For model evaluation
EVAL:
  eval_epoch: best

# Args for Adam optimizer
OPTIMIZER_ARGS:
  lr: 0.001

# For ReduceLRonPlateau
SCHEDULER_ARGS:
  gamma: 0.1
  patience: 200
  threshold: 0.00001
  min_lr : 0.00001

# Path to a pretrained model
PRETRAINED_MODEL: null

# Precomputed descriptors
PRECOMPUTED_DESCRIPTORS: false
