# Define a seed. This is used to shuffle frame indices for cross-validation splits and
# initialize model parameters
SEED: 42

# featomic SphericalExpansion hyperparameters
SPHERICAL_EXPANSION_HYPERS:
  cutoff:
    radius: 3.0
    smoothing:
      type: ShiftedCosine
      width: 0.1
  density:
    type: Gaussian
    width: 0.3
    scaling:
      type: Willatt2018
      exponent: 7
      rate: 1
      scale: 2.0
  basis:
    type: TensorProduct
    max_angular: 5
    radial:
      type: Gto
      max_radial: 7

# Number of CG tensor products to correlate spherical expansion
N_CORRELATIONS: 1

# Max angular momentum to compute in CG products. Anything <
# SPHERICAL_EXPANSION_HYPERS["max_angular"] * (N_CORRELATIONS + 1) loses information but
# speeds up computation.
ANGULAR_CUTOFF: null

# Value to cutoff the overlap matrix (Angstrom)
OVERLAP_CUTOFF: null

# For training the model
TRAIN:
  device: cpu
  dtype: float64  # important for model accuracy
  batch_size: 1
  n_epochs: 501  # number of total epochs to run. End in a 1, i.e. 20001.
  restart_epoch: null  # epoch of last saved checkpoint, or None for no restart
  val_interval: 50  # validate every x intervals
  log_interval: 50  # epoch interval at which to log metrics
  checkpoint_interval: 50  # save model and optimizer state every x intervals

# For evaluating a model checkpoint
EVAL:
  eval_epoch: best
  target_type: ri  # evaluate MAE against SCF ("scf") or RI ("ri") scalar field

# Args for Adam optimizer
OPTIMIZER_ARGS:
  lr: 0.1

# Args for StepLR scheduler
SCHEDULER_ARGS:
  step_size: 10  # NOTE: this is per validation step
  gamma: 0.1

# Training and validation loss function arguments
TRAIN_LOSS_FN_ARGS:  # full, non-truncated loss
  orthogonal: false
  truncated: false
VAL_LOSS_FN_ARGS:  # validation is *always* the full, non-truncated loss
  orthogonal: false
  truncated: false

# Data names, must be compatible with the data expected by the loss functions above
TRAIN_DATA_NAMES:
  target_c: ri_coeffs.npz
  target_w: ri_projs.npz
  overlap: ri_ovlp.npz
VAL_DATA_NAMES:
  target_c: ri_coeffs.npz
  target_w: ri_projs.npz
  overlap: ri_ovlp.npz

# Whether to pass invariant blocks of the descriptor through a learnable layer norm
DESCRIPTOR_LAYER_NORM: False

# Neural network architecture
NN_LAYERS: null

# For masking
GET_SELECTED_ATOMS: null

# Pretrained model for fine-tuning
PRETRAINED_MODEL: null
